# This workflow will do a clean install of node dependencies, build the source
# code and run tests across different versions of node For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

---
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22, 24]
        os: [ubuntu-latest]

    env:
      OS: ${{ matrix.os }}
      NODE: ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - name: Test ${{ matrix.node-version }}
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
